class BeerData {
  static final List<Map<String, dynamic>> beers = [
    {
      'name': 'Castle Lite',
      'type': 'Lager',
      'location': 'South Africa',
      'rating': 3.5,
      'ratingCount': 1200,
      'imagePath': 'assets/clite.jpg',
      'price': 'PRE-ORDER',
    },
    {
      'name': 'Castle',
      'type': 'Lager',
      'location': 'South Africa',
      'rating': 3.2,
      'ratingCount': 950,
      'imagePath': 'assets/castle.jpg',
      'price': '1.50',
    },
    {
      'name': 'Super',
      'type': 'Ale',
      'location': 'South Africa',
      'rating': 4.0,
      'ratingCount': 800,
      'imagePath': 'assets/super.jpg',
      'price': '1.00',
    },
    {
      'name': 'Zambezi',
      'type': 'Lager',
      'location': 'Zimbabwe',
      'rating': 3.8,
      'ratingCount': 600,
      'imagePath': 'assets/zambezi.jpg',
      'price': '1.20',
    },
    {
      'name': 'Savanah',
      'type': 'Lager',
      'location': 'Netherlands',
      'rating': 4.2,
      'ratingCount': 2000,
      'imagePath': 'assets/savana.jpg',
      'price': '2.00',
    },
    {
      'name': 'Nyathi',
      'type': 'Stout',
      'location': 'Zimbabwe',
      'rating': 1.0,
      'ratingCount': 1500,
      'imagePath': 'assets/nyathi.jpg',
      'price': '0.80',
    },
  ];
}
